runtime: python38
# env: flex
entrypoint: gunicorn -b :$PORT main:app
#gunicorn --worker-class eventlet --workers 3 -b :$PORT main:app
#entrypoint: gunicorn -t 0 -b :$PORT main:app
# runtime_config:
#   python_version: 3

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml

#automatic_scaling:
#  min_pending_latency: automatic
#  max_pending_latency: automatic

manual_scaling:
  instances: 2
resources:
  cpu: 8
  memory_gb: 32
  disk_size_gb: 20
#
#liveness_check:
#  path: "/liveness_check"
#  check_interval_sec: 30
#  timeout_sec: 4
#  failure_threshold: 2
#  success_threshold: 2


#runtime: python38
##env: flex
#entrypoint: gunicorn -b :$PORT main:app
#
##runtime_config:
##  python_version: 3
#
## This sample incurs costs to run on the App Engine flexible environment.
## The settings below are to reduce costs during testing and are not appropriate
## for production use. For more information, see:
## https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
##automatic_scaling:
##  target_cpu_utilization: 0.8
##  min_pending_latency: 60ms
##  max_pending_latency: automatic
##  max_concurrent_requests: 50
